/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "lkyaijggzylzhgvamgcf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxreWFpamdnenlsemhndmFtZ2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3OTU1MzMsImV4cCI6MjA5MDM3MTUzM30.wskb8Pc8mzM2j2LdDY-ow-dURZ0--u79YpfZ5nd8aBU"